import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{
      type: 'autogenerated',
      dirName: 'docs'
    }
  ],
  quickSidebar: [{
      type: 'autogenerated',
      dirName: 'quick'
    }
  ],
  releaseSidebar: [{
      type: 'autogenerated',
      dirName: 'release'
    }
  ],
  supportusSidebar: [{
      type: 'autogenerated',
      dirName: 'supportus'
    }
  ],
  shareSidebar: [{
      type: 'autogenerated',
      dirName: 'share'
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
