import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    mainSidebar: [{
        type: 'autogenerated',
        dirName: 'docs'
    }
    ],
    developSidebar: [{
        type: 'autogenerated',
        dirName: 'develop'
    }
    ],
    casesSidebar: [{
        type: 'autogenerated',
        dirName: 'cases'
    }
    ],
    joinSidebar: [{
        type: 'autogenerated',
        dirName: 'join'
    }
    ],
};

export default sidebars;
